# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: public

jobs:
# Please do not rename this job
  build-project:
    name: build bdsb-login-main
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v16.x

      - name: Build Node assets
        env:
          CI: true
          GITHUB_CLIENT_ID: e51d10a63810cbc0fbf2
          GITHUB_CLIENT_SECRET: c2f264fa69801093350502a53e94452b987d0844
          MONGODB_URI: mongodb+srv://RotomongoDB:RotomongoDB@node-angular-cluster.oso6n.mongodb.net/node-angular-cluster
          SITE_URL: ${{ inputs.site-url }}
        run: |
          npm install
          npm run build
          npm run start

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: ea7aa591-c2e9-4f6c-8853-765793d70d45
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/bdsb-login-main/config.yaml
          action: upload
